type Movie {
  id: Int!
  title: String!
  year: Int!
  genre: String
  # genre: [String!]
}

input CreateMovieInput {
  title: String!
  year: Int!
  genre: String
}

type Query {
  getAllMovies: [Movie]
}

type Mutation {
  createMovie(movie: CreateMovieInput): Movie
}
